from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field

class PillarType(str, Enum):
    P1_INFRA_SCAN = "P1_INFRA_SCAN"
    P2_MGRD = "P2_MGRD"
    P3_CMTBP = "P3_CMTBP"
    P4_CAA = "P4_CAA"

class EvidenceType(str, Enum):
    ONION_CRAWL = "ONION_CRAWL"
    NETWORK_PCAP = "NETWORK_PCAP"
    TLS_CERTIFICATE = "TLS_CERTIFICATE"
    BLOCKCHAIN_TX = "BLOCKCHAIN_TX"
    FORUM_DUMP = "FORUM_DUMP"
    PGP_KEY = "PGP_KEY"
    TEXT_SAMPLE = "TEXT_SAMPLE"

class EvidenceRecord(BaseModel):
    """Immutable evidence record conforming to BSA 2023 / Section 65B hash-chain standards."""
    evidence_id: str = Field(description="Unique deterministic evidence identifier")
    evidence_type: EvidenceType
    source_target: str = Field(description="Source identifier (e.g. onion address, txid, forum URL)")
    raw_sha256: str = Field(description="SHA-256 hash of the raw payload")
    byte_size: int
    captured_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    parent_hash: str = Field(description="Hash of previous record in chain of custody")
    block_hash: str = Field(description="Cumulative block hash linking this evidence into the chain")
    metadata: Dict[str, Any] = Field(default_factory=dict)

class InfraScanResult(BaseModel):
    """P1: INFRA-SCAN output."""
    target: str
    jarm_fingerprint: Optional[str] = None
    tls_version: Optional[str] = None
    ssl_subject_common_name: Optional[str] = None
    ssl_san_list: List[str] = Field(default_factory=list)
    open_ports: List[int] = Field(default_factory=list)
    leaked_clearnet_ips: List[str] = Field(default_factory=list)
    confidence_score: float = Field(ge=0.0, le=1.0, description="Pillar confidence score (0.0 to 1.0)")
    indicators: List[str] = Field(default_factory=list)

class MgrdResult(BaseModel):
    """P2: Marketplace Ghost Residue Detection output."""
    persona_alias: str
    correlated_forums: List[str] = Field(default_factory=list)
    pgp_fingerprints: List[str] = Field(default_factory=list)
    temporal_reaction_window_hours: Optional[float] = None
    mirror_cluster_confidence: float = Field(ge=0.0, le=1.0)
    confidence_score: float = Field(ge=0.0, le=1.0)
    evidence_trail: List[str] = Field(default_factory=list)

class CmtbpResult(BaseModel):
    """P3: Crypto Micro-Transaction Breathing Pattern output."""
    wallet_address: str
    cryptocurrency: str = "BTC"
    pre_mixer_micro_txs_detected: int = 0
    mixer_heuristic_signature: Optional[str] = None
    breathing_period_hours: float = 0.0
    utxo_cluster_size: int = 0
    confidence_score: float = Field(ge=0.0, le=1.0)
    flagged_patterns: List[str] = Field(default_factory=list)

class CaaResult(BaseModel):
    """P4: Cognitive Argument Architecture stylometry output."""
    sample_id: str
    lexical_diversity_ttr: float = 0.0
    avg_sentence_length: float = 0.0
    punctuation_signature: Dict[str, float] = Field(default_factory=dict)
    cognitive_marker_matches: List[str] = Field(default_factory=list)
    author_similarity_score: float = Field(ge=0.0, le=1.0)
    confidence_score: float = Field(ge=0.0, le=1.0)

class DacsAttributionReport(BaseModel):
    """Fused attribution report generated by the DACS Scoring Engine."""
    case_id: str
    target_persona: str
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    dacs_score: float = Field(ge=0.0, le=100.0, description="Deterministic Attribution Confidence Score (0-100%)")
    attribution_verdict: str = Field(description="High Confidence Attribution / Moderate / Insufficient Evidence")
    pillar_scores: Dict[str, float] = Field(description="Breakdown of individual pillar scores (0.0 - 1.0)")
    chain_of_custody_hash: str = Field(description="Cumulative BSA 2023 hash anchor")
    evidence_count: int
    key_findings: List[str]
    forensic_notes: str
